name: auto-merge

on:
  workflow_call:
    secrets:
      TOKEN_1PASSWORD:
        description: 1Password service account token
        required: true

jobs:
  auto-merge:
    timeout-minutes: 5

    runs-on: ubuntu-24.04
