name: job-docker-publish

on:
  workflow_call:
    secrets:
      TOKEN_DOCKERHUB:
        description: Docker Hub API token
        required: false

    inputs:
      release:
        description: flag if github release is done
        default: false
        type: boolean

      version:
        description: version to publish
        required: true
        type: string

      alias:
        description: major version to publish
        required: true
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest

    if: ${{ inputs.release }}

    outputs:
      name: ${{ steps.image.outputs.name }}
      exists: ${{ steps.dockerfile.outputs.exists }}

    steps:
      - uses: actions/checkout@v3.6.0

      - id: dockerfile
        run: echo "exists=$([[ -f "${{ github.workspace }}/Dockerfile" ]] && echo true || echo false)" >> "$GITHUB_OUTPUT"

      - id: image
        run: echo "name=$(basename "${GITHUB_REPOSITORY/docker-//}")" >> "$GITHUB_OUTPUT"

  publish-strategy:
    needs: docker

    if: ${{ needs.docker.outputs.exists == 'true' }}

    uses: ./.github/workflows/job-load-matrix.yml
    with:
      matrix: .github/matrix-publish.json

  publish-docker:
    needs:
      - docker
      - publish-strategy

    strategy:
      matrix: ${{ fromJSON(needs.publish-strategy.outputs.matrix) }}

    if: ${{ needs.docker.outputs.exists == 'true' }}

    uses: ./.github/workflows/job-docker-build-push.yml
    with:
      name: ${{ needs.docker.outputs.name }}
      version: ${{ inputs.version }}
      alias: ${{ inputs.alias }}
      platforms: ${{ matrix.platforms }}
      registry: ${{ matrix.registry }}
    secrets:
      password: ${{ secrets[format('TOKEN_{0}', matrix.id)] }}
