name: lint-ci

on: workflow_call

permissions:
  contents: write
  statuses: write
  pull-requests: write

jobs:
  lint-documentation:
    timeout-minutes: 5

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4.2.2

      - uses: oxsecurity/megalinter/flavors/ci_light@v8.4.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
          MEGALINTER_CONFIG: .github/linters/.mega-linter.yml
          GITHUB_COMMENT_REPORTER: true
          GITHUB_STATUS_REPORTER: true
