name: alias-tag

on:
  workflow_call:
    inputs:
      name:
        description: tag name to use
        required: true
        type: string

      sha:
        description: The sha of the commit to use
        required: true
        type: string

permissions:
  contents: write

jobs:
  alias-tag:
    timeout-minutes: 5

    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const tag = 'tags/${{ inputs.name }}'
            const sha = '${{ inputs.sha }}'
            await github.rest.git.deleteRef({ ...context.repo, ref: tag }).catch(() => {})
            await github.rest.git.createRef({ ...context.repo, ref: `refs/${tag}` , sha })
