name: metadata

on:
  workflow_call:
    outputs:
      repository_is_template:
        description: Flag indicating if the repository is a template
        value: ${{ jobs.metadata.outputs.repository_is_template }}

jobs:
  metadata:
    timeout-minutes: 5

    runs-on: ubuntu-latest

    outputs:
      repository_is_template: ${{ steps.metadata.outputs.repository_is_template }}

    steps:
      - uses: actions/checkout@v3.5.3

      - uses: ahmadnassri/action-metadata@v2.1.2
        id: metadata
