name: pull-request-target-template

on: workflow_call

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  template-sync:
    secrets: inherit
    uses: ./.github/workflows/job-template-sync.yml

  auto-merge:
    needs: template-sync
    secrets: inherit
    uses: ./.github/workflows/job-auto-merge.yml
    permissions:
      contents: write
      pull-requests: write
