name: pull-request-target-template

on: workflow_call

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

permissions: read-all

jobs:
  template-sync:
    secrets: inherit
    uses: ahmadnassri/actions/.github/workflows/template-sync.yml@master

  auto-merge:
    needs: template-sync
    secrets: inherit
    uses: ahmadnassri/actions/.github/workflows/auto-merge.yml@master
    permissions:
      contents: write
      pull-requests: write
