name: pull-request-terraform

on:
  workflow_call:
    secrets:
      TOKEN_1PASSWORD:
        description: 1Password service account token
        required: true

      TOKEN_ROTATION:
        description: Rotation Key
        required: false

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  metadata:
    permissions:
      contents: read

    uses: ./.github/workflows/job-metadata.yml

  changed-files:
    permissions:
      contents: read

    uses: ./.github/workflows/job-changed-files.yml
    with:
      pathspec: "*.tf *.hcl data.yml"

  terraform-plan:
    permissions:
      contents: read
      pull-requests: write

    needs:
      - metadata
      - changed-files

    # only runs on non main branch, when terraform files have changed
    if: |
      needs.changed-files.outputs.changed == 'true' &&
      needs.metadata.outputs.repository_default_branch != github.ref_name

    uses: ./.github/workflows/job-terraform-plan.yml
    secrets:
      TOKEN_1PASSWORD: ${{ secrets.TOKEN_1PASSWORD }}
      TOKEN_ROTATION: ${{ secrets.TOKEN_ROTATION }}
