name: pull-request-target

on: workflow_call

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

permissions: read-all

jobs:
  auto-merge:
    secrets: inherit
    uses: ./.github/workflows/auto-merge.yml
    permissions:
      contents: write
      pull-requests: write
