name: pull-request-target-template

on:
  workflow_call:
    secrets:
      TOKEN_1PASSWORD:
        description: 1Password service account token
        required: true

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  template-sync:
    uses: ./.github/workflows/job-template-sync.yml
    secrets:
      TOKEN_1PASSWORD: ${{ secrets.TOKEN_1PASSWORD }}

  auto-merge:
    needs: template-sync
    uses: ./.github/workflows/job-auto-merge.yml
    secrets:
      TOKEN_1PASSWORD: ${{ secrets.TOKEN_1PASSWORD }}
