name: pull-request-target-template

on: workflow_call

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  template-sync:
    uses: ./.github/workflows/job-template-sync.yml
    secrets:
      github-token: ${{ secrets.GH_TOKEN }}

  auto-merge:
    needs: template-sync
    uses: ./.github/workflows/job-auto-merge.yml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
