name: pull-request-terraform

on:
  workflow_call:
    secrets:
      TOKEN_TERRAFORM:
        description: Terraform Cloud API token
        required: true

      TOKEN_CLOUDFLARE:
        description: Cloudflare API token
        required: false

      TOKEN_DOCKERHUB:
        description: Docker Hub API token
        required: false

      TOKEN_GITHUB:
        description: GitHub PAT token
        required: false

      TOKEN_NPM:
        description: NPM API token
        required: false

      TOKEN_GOOGLE:
        description: Google Credentials
        required: false

      TOKEN_ROTATION:
        description: Rotation Key
        required: false

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  metadata:
    permissions:
      contents: read

    uses: ./.github/workflows/job-metadata.yml

  changed-files:
    permissions:
      contents: read

    uses: ./.github/workflows/job-changed-files.yml
    with:
      pathspec: '*.tf *.hcl data.yml'

  terraform-plan:
    permissions:
      contents: read
      pull-requests: write

    needs:
      - metadata
      - changed-files

    # only runs on non main branch, when terraform files have changed
    if: |
      needs.changed-files.outputs.changed == 'true' &&
      needs.metadata.outputs.repository_default_branch != github.ref_name

    uses: ./.github/workflows/job-terraform-plan.yml
    secrets:
      TOKEN_CLOUDFLARE: ${{ secrets.TOKEN_CLOUDFLARE }}
      TOKEN_DOCKERHUB: ${{ secrets.TOKEN_DOCKERHUB }}
      TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
      TOKEN_GOOGLE: ${{ secrets.TOKEN_GOOGLE }}
      TOKEN_NPM: ${{ secrets.TOKEN_NPM }}
      TOKEN_TERRAFORM: ${{ secrets.TOKEN_TERRAFORM }}
      TOKEN_ROTATION: ${{ secrets.TOKEN_ROTATION }}
