name: push-template

on:
  workflow_call:
    secrets:
      TOKEN_GITHUB:
        description: GitHub Personal Access Token
        required: true

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  metadata:
    uses: ./.github/workflows/job-metadata.yml

  lint-commits:
    uses: ./.github/workflows/job-lint-commits.yml

  lint-content:
    uses: ./.github/workflows/job-lint-ci.yml

    permissions:
      contents: write
      statuses: write
      pull-requests: write

  template-sync:
    needs:
      - metadata
      - lint-commits
      - lint-content

    if: ${{ needs.metadata.outputs.repository_default_branch == github.ref_name }}

    uses: ./.github/workflows/job-template-sync.yml
    secrets:
      TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
