name: push-docker

on:
  workflow_call:
    secrets:
      TOKEN_DOCKERHUB:
        description: Docker Hub API token
        required: false

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  metadata:
    uses: ./.github/workflows/job-metadata.yml

  lint-commits:
    uses: ./.github/workflows/job-lint-commits.yml

  lint-content:
    uses: ./.github/workflows/job-lint-all.yml

    permissions:
      contents: write
      statuses: write
      pull-requests: write

  release:
    needs:
      - metadata
      - lint-commits
      - lint-content

    permissions:
      contents: write
      packages: write
      pull-requests: write

    if: ${{ needs.metadata.outputs.repository_default_branch == github.ref_name }}

    uses: ./.github/workflows/job-semantic-release.yml

  publish-config:
    uses: ./.github/workflows/job-parse-json.yml
    with:
      file: .github/docker-config.json

  publish-docker:
    needs:
      - release
      - metadata
      - publish-config

    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/job-docker-build-push.yml
    with:
      name: ${{ fromJson(needs.publish-config.outputs.json).name || needs.metadata.outputs.repository_name }}
      description: ${{ needs.metadata.outputs.repository_description }}
      license: ${{ needs.metadata.outputs.license_spdx_id }}
      version: ${{ needs.release.outputs.release-git-tag }}
      platforms: ${{ fromJson(needs.publish-config.outputs.json).platforms }}
      registries: ${{ toJSON(fromJson(needs.publish-config.outputs.json).registries) }}
    secrets:
      TOKEN_DOCKERHUB: ${{ secrets.TOKEN_DOCKERHUB }}
