name: push

on:
  workflow_call:
    secrets:
      github-token:
        description: GitHub Personal Access Token
        required: true

jobs:
  metadata:
    uses: ./.github/workflows/metadata.yml

  lint-commits:
    uses: ./.github/workflows/lint-commits.yml

  lint-content:
    uses: ./.github/workflows/lint-documentation.yml

    permissions:
      contents: write
      statuses: write
      pull-requests: write

  template-sync:
    needs:
      - metadata
      - lint-commits
      - lint-content

    if: ${{ needs.metadata.outputs.repository_default_branch == github.ref_name }}

    uses: ./.github/workflows/template-sync.yml
    secrets:
      github-token: ${{ secrets.github-token }}
