name: push-javascript

on: workflow_call

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  metadata:
    uses: ./.github/workflows/job-metadata.yml

  lint-commits:
    uses: ./.github/workflows/job-lint-commits.yml

  lint-content:
    uses: ./.github/workflows/job-lint-javascript.yml

    permissions:
      contents: write
      statuses: write
      pull-requests: write

  npm-audit:
    uses: ./.github/workflows/job-npm-audit.yml

  test-strategy:
    uses: ./.github/workflows/job-load-matrix.yml
    with:
      matrix: .github/test-matrix.json

  npm-test:
    needs: test-strategy

    strategy:
      matrix: ${{ fromJSON(needs.test-strategy.outputs.matrix) }}

    uses: ./.github/workflows/job-npm-test.yml
    with:
      name: ${{ matrix.name }}
      os: ${{ matrix.os }}
      node-version: ${{ matrix.node-version }}
      with-browsers: ${{ matrix.with-browsers }}

  release:
    needs:
      - metadata
      - lint-commits
      - lint-content
      - npm-audit
      - npm-test

    permissions:
      contents: write
      packages: write
      pull-requests: write

    if: ${{ needs.metadata.outputs.repository_default_branch == github.ref_name }}

    uses: ./.github/workflows/job-semantic-release.yml
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}

  npm-mirror:
    needs: release

    permissions:
      packages: write

    if: ${{ needs.release.outputs.published == 'true' }}

    uses: ./.github/workflows/job-npm-mirror.yml
    with:
      version: ${{ needs.release.outputs.release-version }}

  publish-docker:
    needs: release

    uses: ./.github/workflows/job-docker-publish.yml
    with:
      release: ${{ needs.release.outputs.published == 'true' }}
      version: ${{ needs.release.outputs.release-version }}
      alias: ${{ needs.release.outputs.release-version-major }}
