name: push-docker

on: workflow_call

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  metadata:
    uses: ./.github/workflows/job-metadata.yml

  lint-commits:
    uses: ./.github/workflows/job-lint-commits.yml

  lint-content:
    uses: ./.github/workflows/job-lint-all.yml

    permissions:
      contents: write
      statuses: write
      pull-requests: write

  release:
    needs:
      - metadata
      - lint-commits
      - lint-content

    permissions:
      contents: write
      packages: write
      pull-requests: write

    if: ${{ needs.metadata.outputs.repository_default_branch == github.ref_name }}

    uses: ./.github/workflows/job-semantic-release.yml

  publish-docker:
    needs: release

    uses: ./.github/workflows/job-docker-publish.yml
    with:
      relase: ${{ needs.release.outputs.published == 'true' }}
      version: ${{ needs.release.outputs.release-version }}
      alias: ${{ needs.release.outputs.release-version-major }}
