name: push-action-docker

on: workflow_call

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  metadata:
    uses: ./.github/workflows/job-metadata.yml

  lint-commits:
    uses: ./.github/workflows/job-lint-commits.yml

  lint-content:
    uses: ./.github/workflows/job-lint-javascript.yml

    permissions:
      contents: write
      statuses: write
      pull-requests: write

  npm-test:
    uses: ./.github/workflows/job-npm-test.yml

  test-build:
    needs:
      - metadata

    uses: ./.github/workflows/job-docker-build-test.yml
    with:
      platforms: linux/amd64

  release:
    needs:
      - metadata
      - lint-commits
      - lint-content
      - test-build
      - npm-test

    permissions:
      contents: write
      packages: write
      pull-requests: write

    if: ${{ needs.metadata.outputs.repository_default_branch == github.ref_name }}

    uses: ./.github/workflows/job-semantic-release.yml

  publish:
    needs:
      - release
      - metadata

    permissions:
      contents: read
      packages: write

    if: ${{ needs.release.outputs.published == 'true' }}

    uses: ./.github/workflows/job-docker-build-push.yml
    with:
      name: ${{ needs.metadata.outputs.repository_name }}
      description: ${{ needs.metadata.outputs.repository_description }}
      license: ${{ needs.metadata.outputs.license_spdx_id }}
      version: ${{ needs.release.outputs.release-version }}
      alias: ${{ needs.release.outputs.release-version-major }}
      platforms: linux/amd64,linux/arm64
      registry: ghcr.io
    secrets:
      password: ${{ secrets.GITHUB_TOKEN }}

  alias:
    needs: release

    if: ${{ needs.release.outputs.published == 'true' }}

    permissions:
      contents: write

    strategy:
      matrix:
        alias:
          - version: v${{ needs.release.outputs.release-version-major }}
          - version: v${{ needs.release.outputs.release-version-major }}.${{ needs.release.outputs.release-version-minor }}

    uses: ./.github/workflows/job-alias-tag.yml
    with:
      name: ${{ matrix.alias.version }}
      sha: ${{ needs.release.outputs.release-git-head }}
