name: push-javascript

on:
  workflow_call:
    secrets:
      TOKEN_NPM:
        description: NPM API token
        required: false

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  metadata:
    uses: ./.github/workflows/job-metadata.yml

  lint-commits:
    uses: ./.github/workflows/job-lint-commits.yml

  lint-content:
    uses: ./.github/workflows/job-lint-javascript.yml

    permissions:
      contents: write
      statuses: write
      pull-requests: write

  npm-audit:
    uses: ./.github/workflows/job-npm-audit.yml

  test-strategy:
    name: load test matrix
    uses: ./.github/workflows/job-load-matrix.yml
    with:
      matrix: .github/matrix-test.json

  npm-test:
    needs: test-strategy

    strategy:
      matrix: ${{ fromJSON(needs.test-strategy.outputs.matrix) }}

    uses: ./.github/workflows/job-npm-test.yml
    with:
      name: ${{ matrix.name }}
      os: ${{ matrix.os || 'latest' }}
      node-version: ${{ matrix.node-version || 'latest' }}
      with-browsers: ${{ matrix.with-browsers || false }}

  release:
    needs:
      - metadata
      - lint-commits
      - lint-content
      - npm-audit
      - npm-test

    permissions:
      contents: write
      packages: write
      pull-requests: write

    if: ${{ needs.metadata.outputs.repository_default_branch == github.ref_name }}

    uses: ./.github/workflows/job-semantic-release.yml

  publish-strategy:
    name: load publish matrix
    uses: ./.github/workflows/job-load-matrix.yml
    with:
      matrix: .github/matrix-publish.json

  npm-publish:
    needs:
      - release
      - publish-strategy

    strategy:
      matrix: ${{ fromJSON(needs.publish-strategy.outputs.matrix) }}

    permissions:
      contents: read
      packages: write

    if: ${{ needs.release.outputs.published == 'true' }}

    uses: ./.github/workflows/job-npm-publish.yml
    secrets:
      token: ${{ matrix.registry.id == 'GITHUB' && secrets.GITHUB_TOKEN || secrets[format('TOKEN_{0}', matrix.registry.id)] }}
    with:
      name: ${{ matrix.registry.name || matrix.name || format('@{0}', github.repository) }}
      registry: ${{ matrix.registry.url }}
      version: ${{ needs.release.outputs.release-version }}
