name: push-docker

on: workflow_call

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  metadata:
    uses: ./.github/workflows/job-metadata.yml

  changed-files:
    uses: ./.github/workflows/job-changed-files.yml
    with:
      pathspec: "*.tf *.hcl data.yml"

  lint-commits:
    uses: ./.github/workflows/job-lint-commits.yml

  lint-content:
    uses: ./.github/workflows/job-lint-terraform.yml

    permissions:
      contents: write
      statuses: write
      pull-requests: write
