name: push-terraform

on:
  workflow_call:
    secrets:
      TOKEN_TERRAFORM:
        description: Terraform Cloud API token
        required: true

      TOKEN_CLOUDFLARE:
        description: Cloudflare API token
        required: false

      TOKEN_DOCKERHUB:
        description: Docker Hub API token
        required: false

      TOKEN_GITHUB:
        description: GitHub PAT token
        required: false

      TOKEN_GOOGLE:
        description: Google Credentials
        required: false

      TOKEN_NPM:
        description: NPM API token
        required: false

      TOKEN_ROTATION:
        description: Rotation Key
        required: false

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  metadata:
    uses: ./.github/workflows/job-metadata.yml

  changed-files:
    uses: ./.github/workflows/job-changed-files.yml
    with:
      pathspec: '*.tf *.hcl data.yml'

  lint-commits:
    uses: ./.github/workflows/job-lint-commits.yml

  lint-content:
    uses: ./.github/workflows/job-lint-terraform.yml

    permissions:
      contents: write
      statuses: write
      pull-requests: write

  terraform-apply:
    needs:
      - metadata
      - changed-files
      - lint-commits
      - lint-content

    # only runs on main branch, when terraform files have changed, or if manually triggered
    if: |
      (
        github.event_name == 'workflow_dispatch' ||
        needs.changed-files.outputs.changed == 'true'
      ) &&
      needs.metadata.outputs.repository_default_branch == github.ref_name

    uses: ./.github/workflows/job-terraform-apply.yml
    secrets:
      TOKEN_CLOUDFLARE: ${{ secrets.TOKEN_CLOUDFLARE }}
      TOKEN_DOCKERHUB: ${{ secrets.TOKEN_DOCKERHUB }}
      TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
      TOKEN_NPM: ${{ secrets.TOKEN_NPM }}
      TOKEN_TERRAFORM: ${{ secrets.TOKEN_TERRAFORM }}
      TOKEN_ROTATION: ${{ secrets.TOKEN_ROTATION }}
