name: push-docker

on: workflow_call

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  metadata:
    uses: ./.github/workflows/job-metadata.yml

  lint-commits:
    uses: ./.github/workflows/job-lint-commits.yml

  lint-content:
    uses: ./.github/workflows/job-lint-terraform.yml

    permissions:
      contents: write
      statuses: write
      pull-requests: write

  release:
    needs:
      - metadata
      - lint-commits
      - lint-content

    permissions:
      contents: write
      packages: write
      pull-requests: write

    if: ${{ needs.metadata.outputs.repository_default_branch == github.ref_name }}

    uses: ./.github/workflows/job-semantic-release.yml
