name: push-action-docker

on:
  workflow_call:
    secrets:
      public-key:
        description: SSH public key
        required: false

      private-key:
        description: SSH private key
        required: false

    inputs:
      sign-commits:
        type: boolean
        default: false
        required: false

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  metadata:
    uses: ./.github/workflows/job-metadata.yml

  image:
    runs-on: ubuntu-latest

    outputs:
      name: ${{ steps.image.outputs.name }}

    steps:
      - id: image
        run: echo "name=$(basename "${GITHUB_REPOSITORY/docker-//}")" >> "$GITHUB_OUTPUT"

  lint-commits:
    uses: ./.github/workflows/job-lint-commits.yml

  lint-content:
    uses: ./.github/workflows/job-lint-all.yml

    permissions:
      contents: write
      statuses: write
      pull-requests: write

  release:
    needs:
      - metadata
      - lint-commits
      - lint-content

    permissions:
      contents: write
      packages: write
      pull-requests: write

    uses: ./.github/workflows/job-semantic-release.yml
    secrets:
      signing-key: ${{ secrets.signing-key }}
    with:
      sign-commits: true
      repository_default_branch: ${{ needs.metadata.outputs.repository_default_branch }}

  publish:
    needs:
      - image
      - release
      - metadata

    if: ${{ needs.release.outputs.published == 'true' }}

    uses: ./.github/workflows/job-docker-build-push.yml
    with:
      name: ${{ needs.image.outputs.name }}
      version: ${{ needs.release.outputs.release-version }}
      alias: ${{ needs.release.outputs.release-version-major }}
      platforms: linux/amd64,linux/arm64
      registry: ghcr.io
    secrets:
      password: ${{ github.token }}

  alias:
    needs: release

    if: ${{ needs.release.outputs.published == 'true' }}

    permissions:
      contents: write

    strategy:
      matrix:
        alias:
          - version: v${{ needs.release.outputs.release-version-major }}
          - version: v${{ needs.release.outputs.release-version-major }}.${{ needs.release.outputs.release-version-minor }}

    uses: ./.github/workflows/job-alias-tag.yml
    with:
      name: ${{ matrix.alias.version }}
