name: pull_request_target

on: pull_request_target

permissions: read-all

jobs:
  main:
    uses: ./.github/workflows/pull-request-target.yml
    secrets:
      TOKEN_1PASSWORD: ${{ secrets.TOKEN_1PASSWORD }}
