name: pull_request_target

on: pull_request_target

permissions: read-all

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  auto-merge:
    uses: ./.github/workflows/job-auto-merge.yml
