name: pull_request_target

on: pull_request_target

permissions: read-all

jobs:
  main:
    uses: ./.github/workflows/pull-request-target.yml
    secrets:
      TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
