name: template sync

on:
  workflow_call:
    inputs:
      repository_default_branch:
        description: The default/main branch of the repository
        default: master
        required: false
        type: string

      repository_is_template:
        description: Flag indicating if the repository is a template
        default: master
        required: false
        type: string

permissions: read-all

jobs:
  sync:
    timeout-minutes: 5

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.3
      - uses: ahmadnassri/action-template-repository-sync@v2.3.4
        with:
          github-token: ${{ secrets.GH_TOKEN }}

