name: template-sync

on:
  workflow_call:
    secrets:
      github-token:
        description: GitHub Personal Access Token
        required: true

jobs:
  template-sync:
    timeout-minutes: 5

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: ahmadnassri/action-template-repository-sync@v2.4.6
        with:
          github-token: ${{ secrets.github-token }}
