name: template-sync

on: workflow_call

permissions: read-all

jobs:
  main:
    timeout-minutes: 5

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: ahmadnassri/action-template-repository-sync@v2.4.6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
