name: template sync

on:
  workflow_call:
    inputs:
      event:
        type: string
        default: main
        required: false

permissions: read-all

jobs:
  sync:
    timeout-minutes: 5

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: ahmadnassri/action-template-repository-sync@v2.4.4
        with:
          event: ${{ inputs.event }}
          github-token: ${{ secrets.GH_TOKEN }}
